source 'https://rubygems.org'


gem 'rails', '4.1.8'

gem 'rails-api'

gem 'spring', :group => :development


gem 'sqlite3'



# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# To use Jbuilder templates for JSON
gem 'jbuilder'

gem 'rack-cors', :require => 'rack/cors'

# To use debugger
gem 'byebug'
